# Note that only one of these targets is required

coins-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: crypto-analytics-2404  #GCP_PROJECT_ID, adjust accordingly
      dataset: "schema" # DBT_DATASET_NAME,  You can also use "schema" here
      threads: 4 # Must be a value of 1 or greater 
